###############################################################################
#
# This dockerfile will build a container for Invoke-Atomicredteam
#
# Usage:
# Build the container
# > docker build -t pwsh .
#
# Running container
# > docker run -it --rm pwsh
# 
# or to persist the container on exit
# > docker run -it --name mypwsh pwsh
# > docker start -i mypwsh
#
# Verify Invoke-Atomicredteam module was importated successfully
# > Invoke-AtomicTest T1113 -ShowDetails
#
###############################################################################

FROM debian:latest

# Install system components
RUN apt update && \
    apt install -y curl gnupg apt-transport-https gss-ntlmssp openssh-client

# Import the public repository GPG keys
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye main" > /etc/apt/sources.list.d/microsoft.list' && \
    apt update && apt install -y powershell && \
    rm /tmp/powershell.tar.gz

# Install Atomicredteam, Attire-ExecutionLogger, and Load Invoke-AtomicRedTeam in profile
RUN pwsh -command "IEX (IWR 'https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1' -UseBasicParsing); Install-AtomicRedTeam -getAtomics -Force;" && \
    mkdir -p ~/loggers && \
    curl -L https://raw.githubusercontent.com/SecurityRiskAdvisors/invoke-atomic-attire-logger/main/Attire-ExecutionLogger.psm1 -o ~/loggers/Attire-ExecutionLogger.psm1 && \
    mkdir -p ~/.config/powershell/ && \
    echo -e 'Import-Module "/root/AtomicRedTeam/invoke-atomicredteam/Invoke-AtomicRedTeam.psd1" -Force\nImport-Module "/root/loggers/Attire-ExecutionLogger.psm1" -Force' > ~/.config/powershell/profile.ps1

# Add For WSMan Authentication Support
RUN pwsh -Command "Install-Module -Name PSWSMan -Force" && \
    pwsh -Command "Install-WSMan"

# Start PowerShell
ENTRYPOINT ["pwsh"]
