###############################################################################
#
# This dockerfile will build a container for Invoke-Atomicredteam
#
# Usage:
# Build the container
# > docker build -t pwsh .
#
# Running container
# > docker run -it --rm pwsh
# 
# or to persist the container on exit
# > docker run -it --name mypwsh pwsh
# > docker start -i mypwsh
#
# Verify Invoke-Atomicredteam module was importated successfully
# > Invoke-AtomicTest T1113 -ShowDetails
#
###############################################################################

FROM debian:latest

# Install system components
RUN apt update && apt install -y curl gnupg apt-transport-https gss-ntlmssp

# Import the public repository GPG keys
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

# Register the Microsoft Product feed
RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye main" > /etc/apt/sources.list.d/microsoft.list'

# Install PowerShell
RUN apt update && apt install -y powershell

# Required for Powershell Remoting over SSH
RUN apt install -y openssh-client

# Install Atomicredteam
RUN pwsh -command "IEX (IWR 'https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1' -UseBasicParsing); Install-AtomicRedTeam -getAtomics -Force;"

# Load Invoke-AtomicRedTeam in profile
RUN mkdir -p ~/.config/powershell/
RUN echo 'Import-Module "/root/AtomicRedTeam/invoke-atomicredteam/Invoke-AtomicRedTeam.psd1" -Force' > ~/.config/powershell/profile.ps1

# Add For WSMan Authentication Support
RUN pwsh -Command "Install-Module -Name PSWSMan -Force"
RUN pwsh -Command "Install-WSMan"

# Cleanup
RUN rm /tmp/powershell.tar.gz

# Start PowerShell
ENTRYPOINT ["pwsh"]
